### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by jonathan-up** [Sarrus1/amxxpawn-vscode#1]
# What do you want to see added to the extension?
Simple and detailed documentation

# How would it help you?
Simple and detailed documentation

# How often would you use this feature?

**Comment by Sarrus1** [comment]
Hello,
Sorry for the late reply.
I have moved the development of this extension to [this repo](https://github.com/Sarrus1/sourcepawn-vscode).
The extension should work now 👍  

You can follow [the documentation for the sourcepawn extension](https://github.com/Sarrus1/sourcepawn-vscode/wiki), which is pretty much the same thing.
