### ISSUE TITLE
What should be next for work?

### ISSUE THREAD

**Issue by wopox1337** [Sarrus1/amxxpawn-vscode#2]
@Sarrus1 Hi! Great, we now have a separate [LSP on Rust](https://github.com/Sarrus1/sourcepawn-lsp), and a separate front for SourcePawn & AMXXPawn, but right now the LSP does not work for AMXXPawn.

**Comment by Sarrus1** [comment]
Hello,
Sorry for the late reply.
I have moved the development of this extension to [this repo](https://github.com/Sarrus1/sourcepawn-vscode).
The extension should work now 👍
